scrape_configs:
  - job_name: 'dotnet_app_1'
    static_configs:
      - targets: ['host.docker.internal:5286']
        labels:
          application: 'dotnet-app-1'
  - job_name: 'dotnet_app_2'
    static_configs:
      - targets: ['host.docker.internal:5212']
        labels:
          application: 'dotnet-app-2'
  - job_name: 'dotnet_app_3'
    static_configs:
      - targets: ['host.docker.internal:5115']
        labels:
          application: 'dotnet-app-3'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']